---
- name: Distribute SSH key to all targets
  hosts: all
  become: true
  vars:
    ansible_ssh_pass: "password"
  tasks:
    - name: Ensure the public SSH key is present
      authorized_key:
        user: "{{ ansible_user | default('root') }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
